# Generated by Django 4.2 on 2026-01-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("logo", "Logo Design"),
                            ("social", "Social Media"),
                            ("flyer", "Flyer/Poster"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "features",
                    models.TextField(help_text="Enter features separated by new lines"),
                ),
                (
                    "delivery_time",
                    models.CharField(default="3-5 business days", max_length=100),
                ),
                ("revisions", models.IntegerField(default=2)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="packages/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "price"],
            },
        ),
    ]
