# Generated by Django 4.2 on 2026-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="hero/")),
                ("cta_text", models.CharField(default="View Packages", max_length=50)),
                ("cta_link", models.CharField(default="/packages/", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Hero Sections",
                "ordering": ["-created_at"],
            },
        ),
    ]
